# Candace Savonen Apr 2022

name: Build Docker Image

on:
  workflow_call:
    inputs:
      directory:
        required: true
        type: string
      tag:
        required: true
        type: string
      dockerhubpush:
        description: 'Push to Dockerhub?'
        required: false
        default: 'false'
        type: string
    secrets:
      GH_PAT:
        required: true
      DOCKERHUB_USERNAME:
        required: false
      DOCKERHUB_TOKEN:
        required: false

defaults:
  run:
    working-directory: ./

jobs:

  build-docker:
    name: Build Docker image
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      # Set up Docker build
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Setup layer cache
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build
        uses: docker/build-push-action@v4
        with:
          push: false
          context: ${{ inputs.directory }}
          file: ${{ inputs.directory }}/Dockerfile
          platforms: linux/amd64
          tags: ${{ inputs.tag }}

      # Login to Dockerhub
      - name: Login to DockerHub
        if: ${{ inputs.dockerhubpush != 'false' }}
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Push the Docker image if set to true from a manual trigger
      - name: Push Docker image if manual trigger set to true
        if: ${{ inputs.dockerhubpush != 'false' }}
        run: docker push ${{ inputs.tag }}
