# Candace Savonen Jan 2025

name: Pull Request

on:
  push:
    branches: [ main ]

jobs:

  dockerfile-check:
    name: Detect changed Dockerfile - ${{ matrix.config.dir }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        config:
          - {dir: base_ottr,   name: 'jhudsl/base_ottr'}
          - {dir: ottrpal,   name: 'jhudsl/ottrpal'}
          - {dir: bioconductor,   name: 'jhudsl/ottr_bioconductor'}
          - {dir: ottr_website,   name: 'jhudsl/ottr_website'}
# NEW IMAGES HERE: #
#######   - {dir: directory_path,   name: 'name its called on dockerhub'}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get specific changed files
        id: image_name
        uses: tj-actions/changed-files@v14.5
        with:
          files: ${{ matrix.config.dir }}/*

      - run: echo ${{steps.image_name.outputs.any_changed}}

  build-it:
    name: Build it
    needs: dockerfile-check
    if: ${{needs.dockerfile-check.outputs.any_changed == 'true'}}
    uses: jhudsl/ottr-docker/.github/workflows/docker-test.yml@main
    with:
      directory: ${{ matrix.config.dir }}
      tag: ${{ matrix.config.name }}
      dockerhubpush: true
    secrets:
      GH_PAT: ${{ secrets.GH_PAT }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
