# Candace Savonen May 2022

name: Pull Request

on:
  push:
    branches: [ main ]

jobs:

  files-changed:
    name: Detect changed Dockerfiles
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Base ottr changed?
        uses: tj-actions/verify-changed-files@v8.8
        id: base_ottr-changed
        with:
          files: |
             base_ottr/Dockerfile
             base_ottr/github_package_list.tsv

      - name: Base ottr changed?
        uses: tj-actions/verify-changed-files@v8.8
        id: ottrpal-changed
        with:
          files: ottrpal/Dockerfile

      - name: Bioconductor image changed?
        uses: tj-actions/verify-changed-files@v8.8
        id: bioconductor-changed
        with:
          files: bioconductor/*

    outputs:
      base_change: steps.verify-changed-files.outputs.base_ottr-changed
      ottrpal_change: steps.verify-changed-files.outputs.ottrpal-changed
      bioconductor_change: steps.files-changed.outputs.bioconductor-changed

  build-base:
    name: Build base ottr image
    needs: dockerfiles-changed
    if: ${{needs.dockerfiles-changed.outputs.base_ottr_changed == 'true'}}
    uses: ./.github/workflows/docker-test.yml
    with:
      directory: base_ottr
      tag: jhudsl/course_template
      dockerhubpush: true
    secrets:
      GH_PAT: ${{ secrets.GH_PAT }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  build-ottrpal:
    name: Build ottrpal image
    needs: dockerfiles-changed
    if: ${{needs.dockerfiles-changed.outputs.ottrpal_changed == 'true'}}
    uses: ./.github/workflows/docker-test.yml
    with:
      directory: ottrpal
      tag: jhudsl/ottrpal
      dockerhubpush: true
    secrets:
      GH_PAT: ${{ secrets.GH_PAT }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  build-bioconductor:
    name: Build bioconductor image
    needs: dockerfiles-changed
    if: ${{needs.dockerfiles-changed.outputs.bioconductor_changed == 'true'}}
    uses: ./.github/workflows/docker-test.yml
    with:
      directory: bioconductor
      tag: jhudsl/ottr_bioconductor
      dockerhubpush: true
    secrets:
      GH_PAT: ${{ secrets.GH_PAT }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
