# Candace Savonen May 2022

name: Pull Request

on:
  push:
    branches: [ main ]

jobs:

  dockerfiles-changed:
    name: Detect changed Dockerfiles
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get specific changed files
        id: base_ottr
        uses: tj-actions/changed-files@v14.5
        with:
          files: base_ottr/*

      - name: Get specific changed files
        id: ottrpal
        uses: tj-actions/changed-files@v14.5
        with:
          files: ottrpal/*

      - name: Get specific changed files
        id: bioconductor
        uses: tj-actions/changed-files@v14.5
        with:
          files: bioconductor/*

      - run: |
          echo ${{steps.base_ottr.outputs.any_changed}}
          echo ${{steps.ottrpal.outputs.any_changed}}
          echo ${{steps.bioconductor.outputs.any_changed}}

    outputs:
      base_ottr_changed: ${{steps.base_ottr.outputs.any_changed}}
      ottrpal_changed: ${{steps.ottrpal.outputs.any_changed}}
      bioconductor_changed: ${{steps.bioconductor.outputs.any_changed}}

  build-base:
    name: Build base ottr image
    needs: dockerfiles-changed
    if: ${{needs.dockerfiles-changed.outputs.base_ottr_changed == 'true'}}
    uses: ./.github/workflows/docker-test.yml
    with:
      directory: base_ottr
      tag: jhudsl/course_template
      dockerhubpush: true
    secrets:
      GH_PAT: ${{ secrets.GH_PAT }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  build-ottrpal:
    name: Build ottrpal image
    needs: dockerfiles-changed
    if: ${{needs.dockerfiles-changed.outputs.ottrpal_changed == 'true'}}
    uses: ./.github/workflows/docker-test.yml
    with:
      directory: ottrpal
      tag: jhudsl/ottrpal
      dockerhubpush: true
    secrets:
      GH_PAT: ${{ secrets.GH_PAT }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  build-bioconductor:
    name: Build bioconductor image
    needs: dockerfiles-changed
    if: ${{needs.dockerfiles-changed.outputs.bioconductor_changed == 'true'}}
    uses: ./.github/workflows/docker-test.yml
    with:
      directory: bioconductor
      tag: jhudsl/ottr_bioconductor
      dockerhubpush: true
    secrets:
      GH_PAT: ${{ secrets.GH_PAT }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
