# Candace Savonen Jan 2025

name: Pull Request

on:
  push:
    branches: [ main ]

jobs:

  dockerfile-check:
    name: Detect changed Dockerfile - ${{ matrix.config.dir }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        config:
          - {dir: base_ottr,   name: 'jhudsl/base_ottr'}
          - {dir: ottrpal,   name: 'jhudsl/ottrpal'}
          - {dir: bioconductor,   name: 'jhudsl/ottr_bioconductor'}
          - {dir: ottr_website,   name: 'jhudsl/ottr_website'}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get specific changed files
        id: image_name
        uses: tj-actions/changed-files@v14.5
        with:
          files: ${{ matrix.config.dir }}/*

      - run: echo ${{steps.image_name.outputs.any_changed}}

      - name: Build it
        uses: ./.github/workflows/docker-test.yml
        if: ${{steps.image_name.outputs.any_changed == 'true'}}
        with:
          tag: ${{ matrix.config.name }}
          dockerhubpush: true
        secrets:
          GH_PAT: ${{ secrets.GH_PAT }}
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
