# Candace Savonen Jan 2025

name: Pull Request

on:
  pull_request:
    branches: [ main, staging ]

jobs:

  dockerfile-check:
    name: Test changed Dockerfile - ${{ matrix.config.dir }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config:
          - {dir: base_ottr,   name: 'jhudsl/base_ottr'}
          - {dir: ottrpal,   name: 'jhudsl/ottrpal'}
          - {dir: bioconductor,   name: 'jhudsl/ottr_bioconductor'}
          - {dir: ottr_website,   name: 'jhudsl/ottr_website'}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get specific changed files
        id: image_name
        uses: tj-actions/changed-files@v14.5
        with:
          files: ${{ matrix.config.dir }}/*

      - run: |
          echo ${{ steps.image_name.outputs.any_changed }}
          echo ${{ matrix.config.dir }}
          echo "${{ matrix.config.dir }}_changed=${{ steps.image_name.outputs.any_changed }}" >> $GITHUB_OUTPUT

  build-it:
    name: Build image - ${{ matrix.config.dir }}
    needs: dockerfile-check
    if: ${{needs.dockerfile-check.outputs.${{ matrix.config.dir }}_changed == 'true'}}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config:
          - {dir: base_ottr, name: 'jhudsl/base_ottr'}
          - {dir: ottrpal, name: 'jhudsl/ottrpal'}
          - {dir: bioconductor, name: 'jhudsl/ottr_bioconductor'}
          - {dir: ottr_website, name: 'jhudsl/ottr_website'}

    uses: jhudsl/ottr-docker/.github/workflows/docker-test.yml@main
    with:
      directory: ${{ matrix.config.dir }}
      tag: ${{ matrix.config.name }}
      dockerhubpush: false
    secrets:
      GH_PAT: ${{ secrets.GH_PAT }}
