# Candace Savonen May 2022

name: Pull Request

on:
  pull_request:
    branches: [ main, staging ]

jobs:

  dockerfiles-changed:
    name: Detect changed Dockerfiles
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get specific changed files
        uses: tj-actions/changed-files@v14.5
        with:
          files: |
            base_ottr
            ottrpal
            bioconductor

      - name:
        id: folders_changed
        run: |
          if [[ "$steps.folders_changed.outputs.all_changed_and_modified_files" == *"base_ottr"* ]]; then
            echo "::set-output name=base_ottr::true"
          fi

          if [[ "$steps.folders_changed.outputs.all_changed_and_modified_files" == *"ottrpal"* ]]; then
            echo "::set-output name=ottrpal::true"
          fi

          if [[ "$steps.folders_changed.outputs.all_changed_and_modified_files" == *"bioconductor"* ]]; then
            echo "::set-output name=bioconductor::true"
          fi

    outputs:
      base_ottr-changed: steps.folders_changed.outputs.base_ottr
      ottrpal-changed: steps.folders_changed.outputs.ottrpal
      bioconductor-changed: steps.folders_changed.outputs.bioconductor

  build-base:
    name: Build base ottr image
    needs: dockerfiles-changed
    if: ${{needs.dockerfiles-changed.outputs.base_ottr-changed == 'true'}}
    uses: ./.github/workflows/docker-test.yml
    with:
      directory: base_ottr
      tag: jhudsl/course_template
    secrets:
      GH_PAT: ${{ secrets.GH_PAT }}

  build-ottrpal:
    name: Build ottrpal image
    needs: dockerfiles-changed
    if: ${{needs.dockerfiles-changed.outputs.ottrpal-changed == 'true'}}
    uses: ./.github/workflows/docker-test.yml
    with:
      directory: ottrpal
      tag: jhudsl/ottrpal
    secrets:
      GH_PAT: ${{ secrets.GH_PAT }}

  build-bioconductor:
    name: Build bioconductor image
    needs: dockerfiles-changed
    if: ${{needs.dockerfiles-changed.outputs.bioconductor-changed == 'true'}}
    uses: ./.github/workflows/docker-test.yml
    with:
      directory: bioconductor
      tag: jhudsl/ottr_bioconductor
    secrets:
      GH_PAT: ${{ secrets.GH_PAT }}
