# Candace Savonen Jan 2025

name: Pull Request

on:
  pull_request:
    branches: [ main, staging ]

jobs:

  dockerfile-check:
    name: Test changed Dockerfile - ${{ matrix.config.dir }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config:
          - {dir: base_ottr,   name: 'jhudsl/base_ottr'}
          - {dir: ottrpal,   name: 'jhudsl/ottrpal'}
          - {dir: bioconductor,   name: 'jhudsl/ottr_bioconductor'}
          - {dir: ottr_website,   name: 'jhudsl/ottr_website'}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get specific changed files
        id: image_name
        uses: tj-actions/changed-files@v14.5
        with:
          files: ${{ matrix.config.dir }}/*

      - run: |
          echo ${{ steps.image_name.outputs.any_changed }}
          echo ${{ matrix.config.dir }}

      - name: Docker build
        if: ${{ steps.image_name.outputs.any_changed == 'true'}}
        uses: ./.github/workflows/
        with:
          directory: ${{ matrix.config.dir }}
          tag: ${{ matrix.config.name }}
          dockerhubpush: false
          token: ${{ secrets.GH_PAT }}
          dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
