# Candace Savonen May 2022

name: Pull Request

on:
  pull_request:
    branches: [ main, staging ]

jobs:

  dockerfiles-changed:
    name: Detect changed Dockerfiles
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get specific changed files
        id: folders_changed
        uses: tj-actions/changed-files@v14.5
        with:
          files: |
            base_ottr/*
            ottrpal/*
            bioconductor/*

    outputs:
      base_ottr-changed: contains(steps.dockerfiles-changed.outputs.folders_changed, 'base_ottr')
      ottrpal-changed: contains(steps.dockerfiles-changed.outputs.folders_changed, 'ottrpal')
      bioconductor-changed: contains(steps.dockerfiles-changed.outputs.folders_changed, 'bioconductor')

  build-base:
    name: Build base ottr image
    needs: dockerfiles-changed
    if: ${{needs.files-changed.outputs.base_ottr-changed == 'true'}}
    uses: ./.github/workflows/docker-test.yml
    with:
      directory: base_ottr
      tag: jhudsl/course_template
    secrets:
      GH_PAT: ${{ secrets.GH_PAT }}

  build-ottrpal:
    name: Build ottrpal image
    needs: dockerfiles-changed
    if: ${{needs.files-changed.outputs.ottrpal-changed == 'true'}}
    uses: ./.github/workflows/docker-test.yml
    with:
      directory: ottrpal
      tag: jhudsl/ottrpal
    secrets:
      GH_PAT: ${{ secrets.GH_PAT }}

  build-bioconductor:
    name: Build bioconductor image
    needs: dockerfiles-changed
    if: ${{needs.files-changed.outputs.bioconductor-changed == 'true'}}
    uses: ./.github/workflows/docker-test.yml
    with:
      directory: bioconductor
      tag: jhudsl/ottr_bioconductor
    secrets:
      GH_PAT: ${{ secrets.GH_PAT }}
