# Candace Savonen May 2022

name: Pull Request

on:
  pull_request:
    branches: [ main, staging ]

jobs:

  build-base:
    uses: ./.github/workflows/docker-test.yml@main
    with:
      directory: base_ottr
      tag: jhudsl/course_template
    secrets:
      GH_PAT: ${{ secrets.GH_PAT }}

  build-ottrpal:
    uses: ./.github/workflows/docker-test.yml@main
    with:
      directory: ottrpal
      tag: jhudsl/ottrpal
    secrets:
      GH_PAT: ${{ secrets.GH_PAT }}
