# Candace Savonen May 2022

name: Pull Request

on:
  pull_request:
    branches: [ main, staging ]



jobs:

  files-changed:
    name: Detect changed Dockerfiles
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Base ottr changed?
        uses: tj-actions/verify-changed-files@v8.8
        id: base_ottr-changed
        with:
          files: |
             base_ottr/Dockerfile
             base_ottr/github_package_list.tsv

      - name: Base ottr changed?
        uses: tj-actions/verify-changed-files@v8.8
        id: ottrpal-changed
        with:
          files: ottrpal/Dockerfile

    outputs:
      base_change: steps.verify-changed-files.outputs.base_ottr-changed
      ottrpal_change: steps.verify-changed-files.outputs.ottrpal-changed

  build-base:
    name: Build base ottr image
    needs: files-changed
    uses: ./.github/workflows/docker-test.yml
    with:
      directory: base_ottr
      tag: jhudsl/course_template
    secrets:
      GH_PAT: ${{ secrets.GH_PAT }}

  build-ottrpal:
    name: Build ottrpal image
    needs: files-changed
    uses: ./.github/workflows/docker-test.yml
    with:
      directory: ottrpal
      tag: jhudsl/ottrpal
    secrets:
      GH_PAT: ${{ secrets.GH_PAT }}
